server:
    port: 8081
mybatis:
    mapper-locations: classpath:mapper/*.xml
spring:
    shardingsphere:
        datasource:
            ds-0:
                driver-class-name: com.mysql.cj.jdbc.Driver
                jdbc-url: jdbc:mysql://localhost:3306/ds_shop_0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
                password: root
                type: com.zaxxer.hikari.HikariDataSource
                username: root
            ds-1:
                driver-class-name: com.mysql.cj.jdbc.Driver
                jdbc-url: jdbc:mysql://localhost:3306/ds_shop_1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
                password: root
                type: com.zaxxer.hikari.HikariDataSource
                username: root
            names: ds-0,ds-1
        props:
            sql:
                show: true
        sharding:
            binding-tables: t_order,t_order_detail
            default-database-strategy:
                inline:
                    algorithm-expression: ds-$->{user_id % 2}
                    sharding-column: user_id
            tables:
                t_order:
                    actual-data-nodes: ds-$->{0..1}.t_order_$->{0..1}
                    key-generator:
                        column: id
                        props:
                            worker:
                                id: 123
                        type: SNOWFLAKE
                    table-strategy:
                        inline:
                            algorithm-expression: t_order_$->{id % 2}
                            sharding-column: id
                t_order_detail:
                    actual-data-nodes: ds-$->{0..1}.t_order_detail_$->{0..1}
                    key-generator:
                        column: id
                        props:
                            worker:
                                id: 123
                        type: SNOWFLAKE
                    table-strategy:
                        inline:
                            algorithm-expression: t_order_detail_$->{order_id % 2}
                            sharding-column: order_id
